version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-eks
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-irsa
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-keycloak
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-keycloak-configuration
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-keycloak-realm
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/aws-secretsmanager
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-core
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-eks-cluster-autoscaler
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-eks-external-dns
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-eks-lb-controller
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-eks-oidc-service-account
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-flux
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-flux-extras
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-istio
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: modules/k8s-ocp-core
    schedule:
      interval: monthly
