apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: source-controller
    namespace: flux-system
  spec:
    template:
      spec:
        securityContext:
          fsGroup: 1337
          runAsUser: 100
          runAsGroup: 101
