name: Terraform docs

on:
  pull_request:
    paths:
      - "**/*.tf"
  push:
    paths:
      - "**/*.tf"

jobs:
  terraform-docs:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform docs for module folders
        uses: terraform-docs/gh-actions@main
        with:
          recursive: true

      - name: Discarding root README.md update
        run: |
          # restoring staged changes
          git restore --staged README.md
          # discarding changes
          git restore README.md

      - name: Commit updated README.md files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "terraform-docs: automated action"
