name: Terraform docs

on:
  pull_request:
    paths:
      - "**/*.tf"

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform docs for module folders
        uses: terraform-docs/gh-actions@main
        with:
          #git-push: true
          recursive: true

      - name: Debug
        run: |
          git status
